#!/bin/sh

# Add an overlay to a background
# set as wallpaper

BACKGROUND_LOC=$HOME/.config/customwall/background
FOREGROUND_LOC=$HOME/.config/customwall/foreground

cd ~/.cache || exit 1

cp "$(find "$BACKGROUND_LOC" | shuf -n1)" bg.png
cp "$(find "$FOREGROUND_LOC" | shuf -n1)" fg.png

convert fg.png -alpha on -background none -gravity center -gravity center -extent 1920x1080 fg.png
convert bg.png -channel RGB -negate invert.png
convert fg.png invert.png -compose Multiply -composite out.png
composite out.png bg.png wall.png

rm bg.png
rm fg.png
rm invert.png
rm out.png
xwallpaper --center wall.png