#!/bin/bash
#Author: Mike Vandersanden

I3MSG=$(command -v i3-msg) || exit 1
JQ=$(command -v jq) || exit 2

WORKSPACES=$($I3MSG -t get_tree | $JQ '.nodes | .[] | select(.name != "__i3") | .nodes | .[] | select(.type == "con") | .nodes | .[]')

NAMES=($(echo $WORKSPACES | $JQ .name ))

for name in ${NAMES[@]}
do
    OBJ=$(echo $WORKSPACES | $JQ "select(.name == $name)")
    NAME=$(echo $OBJ | $JQ '.num')
    APPS=($(echo $OBJ | $JQ '.nodes | .[] | .window_properties.class' | tr -d '"'))

    i=0
    while [[ i -lt ${#APPS[@]} ]]
    do
        app=${APPS[i]}
        echo $app
        if [ $app == "null" ]
            then
                newAPPS=()
                nullNODES=$(echo $OBJ | $JQ '.nodes | .[] | .nodes | .[]')
                nullAPPS=($(echo $nullNODES | $JQ '.window_properties.class' | tr -d '"'))

                for nullAPP in ${nullAPPS[@]}
                do
                    if [ $nullAPP != "null" ]
                        then
                            newAPPS+=($nullAPP)
                    else
                        lastAPPS=($(echo $nullNODES | $JQ '.nodes | .[] | .window_properties.class' | tr -d '"'))
                        for lastAPP in ${lastAPPS[@]}
                        do
                            if [ $lastAPP != "null" ]
                                then
                                    newAPPS+=($lastAPP)
                            fi

                        done
                    fi 
                done
                APPS+=(${newAPPS[@]})
        fi

        case $app in
            "discord")
                NAME+=""
                ;;
            "Xfce4-terminal")
                NAME+=""
                ;;
            "Code")
                NAME+=""
                ;;
            "Gimp")
                NAME+=""
                ;;
            "Spotify")
                NAME+=""
                ;;
            "Chromium")
                NAME+=""
                ;;
            "Tasque")
                NAME+=""
                ;;
            "Thunar")
                NAME+=""
                ;;
            "Evince")
                NAME+=""
                ;;
            "mpv")
                NAME+=""
                ;;
        esac
        i=$(( $i + 1 ))
    done
    $I3MSG rename workspace $name to $NAME
done
