#!/bin/sh
#Author: Mike Vandersanden

#colors
bold="$(tput bold)"
reset="$(tput sgr0)"
black="$(tput setaf 0)"
gray="$(tput setaf 8)"
red="$(tput setaf 1)"
orange="$(tput setaf 9)"
green="$(tput setaf 2)"
lightgreen="$(tput setaf 10)"
brown="$(tput setaf 3)"
yellow="$(tput setaf 11)"
darkblue="$(tput setaf 4)"
blue="$(tput setaf 12)"
violet="$(tput setaf 5)"
pink="$(tput setaf 13)"
teal="$(tput setaf 6)"
cyan="$(tput setaf 14)"
lightgray="$(tput setaf 7)"
white="$(tput setaf 15)"

#colorlist
colors=(
""
"${reset}${black}0110${reset}"
"${reset}${gray}0010${reset}"
"${reset}${red}0110${reset}"
"${reset}${orange}0101${reset}"
"${reset}${brown}0110${reset}"
"${reset}${yellow}1100${reset}"
"${reset}${green}0110${reset}"
"${reset}${lightgreen}1100${reset}"
"${reset}${darkblue}0110${reset}"
"${reset}${blue}0001${reset}"
"${reset}${teal}0111${reset}"
"${reset}${cyan}0100${reset}"
"${reset}${violet}0110${reset}"
"${reset}${pink}1111${reset}"
"${reset}${lightgray}0111${reset}"
"${reset}${white}0010${reset}"
)

#logo
logo=(
"${reset}            ${darkblue}/${blue}@@@@@@@@@@@@@@@${darkblue}\           ${reset}"
"${reset}           ${darkblue}/${blue}@${darkblue}/${orange}<><><>${yellow}-${orange}<><><>${darkblue}\\${blue}@${darkblue}\          ${reset}"
"${reset}          ${darkblue}/${blue}@${darkblue}/${orange}><><><>${yellow}-${orange}<><><><${darkblue}\\${blue}@${darkblue}\         ${reset}"
"${reset}         ${darkblue}/${blue}@${darkblue}/${cyan}@@@@@@@@@@@@@@@@@${darkblue}\\${blue}@${darkblue}\        ${reset}"
"${reset}        ${darkblue}/${blue}@${darkblue}/${cyan}@@@@@@@@@@@@@@@@@@@${darkblue}\\${blue}@${darkblue}\       ${reset}"
"${reset}       ${darkblue}/${blue}@${darkblue}/${cyan}@@@@              @@@${darkblue}\\${blue}@${darkblue}\      ${reset}"
"${reset}      ${darkblue}/${blue}@${darkblue}/${cyan}@@@@               (@@@${darkblue}\\${blue}@${darkblue}\     ${reset}"
"${reset}     ${darkblue}/${blue}@${darkblue}/${cyan}@@@@@   ${white}__      __${reset}  ${cyan}(@@@@${darkblue}\\${blue}@${darkblue}\    ${reset}"
"${reset}    ${darkblue}|${blue}@${darkblue}|${teal}#${cyan}@@@@@  ${white}${bold}@@@     @@@${reset}  ${cyan}(@@@@#${darkblue}|${blue}@${darkblue}|   ${reset}"
"${reset}    ${darkblue}|${blue}@${darkblue}|${green}${bold}+${reset}${teal}##${cyan}@@@      ${white}${bold}<${reset}        ${cyan}(@@${teal}##${green}${bold}+${reset}${darkblue}|${blue}@${darkblue}|   ${reset}"
"${reset}    ${darkblue}|${blue}@${darkblue}|${teal}##${green}${bold}+${reset}${teal}##${cyan}@@@@@       (@@@@##${green}${bold}+${reset}${teal}##${darkblue}|${blue}@${darkblue}|   ${reset}"
"${reset}    ${darkblue}|${blue}@${darkblue}|${teal}#${green}${bold}+${reset}${teal}###${cyan}@@@@@ ${white}${bold}||||${reset} ${cyan}(@@@@@${teal}###${green}${bold}+${reset}${teal}#${darkblue}|${blue}@${darkblue}|   ${reset}"
"${reset}     ${darkblue}\\${blue}@${darkblue}\\${teal}###${green}${bold}+${reset}${teal}##${cyan}@@@ ${white}${bold}⁻⁻⁻⁻${reset} ${cyan}(@@@${teal}##${green}${bold}+${reset}${teal}###${darkblue}/${blue}@${darkblue}/    ${reset}"
"${reset}       ${darkblue}\\${blue}@${darkblue}\\${green}${bold}+${reset}${teal}###${cyan}@@@@@@@@@@@@@${teal}###${green}${bold}+${reset}${darkblue}/${blue}@${darkblue}/      ${reset}"
"${reset}         ${darkblue}\\${blue}@${darkblue}\\${teal}#${green}${bold}+${reset}${teal}##${cyan}@@@@@@@@@${teal}##${green}${bold}+${reset}${teal}#${darkblue}/${blue}@${darkblue}/        ${reset}"
"${reset}           ${darkblue}\\${blue}@${darkblue}\\${violet}>${green}${bold}+${reset}${violet}<><>${pink}-${violet}<><>${green}${bold}+${reset}${violet}<${darkblue}/${blue}@${darkblue}/          ${reset}"
"${reset}             ${darkblue}\\${blue}@${darkblue}\\${violet}<><>${pink}-${violet}<><>${darkblue}/${blue}@${darkblue}/            ${reset}"
"${reset}               ${darkblue}\\${blue}@@@@@@@@@${darkblue}/              ${reset}"	
)



#"            /@@@@@@@@@@@@@@@\           "
#"           /@/<><><>-<><><>\@\          "
#"          /@/><><><>-<><><><\@\         "
#"         /@/@@@@@@@@@@@@@@@@@\@\        "
#"        /@/@@@@@@@@@@@@@@@@@@@\@\       "
#"       /@/@@@@              @@@\@\      "
#"      /@/@@@@               (@@@\@\     "
#"     /@/@@@@@   __      __  (@@@@\@\    "
#"    |@|#@@@@@  @@@     @@@  (@@@@#|@|   "
#"    |@|+##@@@      <        (@@##+|@|   "
#"    |@|##+##@@@@@       (@@@@##+##|@|   "
#"    |@|#+###@@@@@ |||| (@@@@@###+#|@|   "
#"     \@\###+##@@@ ⁻⁻⁻⁻ (@@@##+###/@/    "
#"       \@\+###@@@@@@@@@@@@@###+/@/      "
#"         \@\#+##@@@@@@@@@##+#/@/        "
#"           \@\>+<><>-<><>+</@/          "
#"             \@\<><>-<><>/@/            "
#"               \@@@@@@@@@/              "

#data
data=(
""	#empty line to start
)

#retrieve data


#print everything
for i in ${!logo[@]}; do printf "%s\t%s\t%s\n" "${colors[$i]}" "${logo[$i]}" "${data[$i]}"; done
