#!/bin/bash
#Author: Mike Vandersanden

CONFIG=$HOME/.config/scrot/iscrot.conf

if ! [ -f $CONFIG ]; then
	mkdir -p $(dirname $CONFIG)
    echo "OUTDIR=$(xdg-user-dir PICTURES)" > $CONFIG
fi

source $CONFIG

if ! [ -d $OUTDIR ]; then
    mkdir -p $OUTDIR
fi

cd $OUTDIR

toclip=0

for var in "${@:1}"
do

case $var in

	-x)
	toclip=1
	;;

	*)
	params+=$var
	;;
esac

done

if [ $toclip == 1 ]
then
	scrot "$params" -e 'xclip -selection clipboard -target image/png -i $f'
else
	scrot "$params"
fi
