#!/bin/sh

rm -f /tmp/locked.png

cp ~/.cache/wall.png /tmp/base.png

if ! [ -f /tmp/base.png ]; then
	convert -size 1920x1080 xc:black /tmp/base.png
fi

# If `imagemagick` is not installed, use a blank screen.
[ -f /usr/bin/convert ] &&
#rm -f /tmp/base.png && scrot -m -z /tmp/base.png &&
pgrep -x dunst && notify-send -i security-high-symbolic.symbolic "Locking computer..." &&
convert /tmp/base.png -grayscale rec709luma -blur 0x8 /tmp/locked.png #grayscale
#convert /tmp/base.png -level 25%\! -blur 0x8 /tmp/locked.png #less color
#convert /tmp/base.png +level-colors ,Teal -blur 0x8 /tmp/locked.png #tealscale
#convert /tmp/base.png +level-colors ,Red -blur 0x8 /tmp/locked.png #redscale

#add text
motd
convert /tmp/locked.png -gravity northwest -fill '#11111180' -pointsize 110 -font '/usr/share/fonts/TTF/DejaVuSans.ttf' -annotate +50+250 'Locked' -gravity southeast -fill '#FFFFFFAA' -pointsize 20 -font '/usr/share/fonts/TTF/DejaVuSans.ttf' -annotate +50+250 "$(cat /tmp/motd)" /tmp/locked.png

#fprintled 2 red &

i3lock -t -f -c 000000 -i /tmp/locked.png

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
#maptouchscreen
