#!/bin/sh

rm -f /tmp/locked.png

# If `imagemagick` is not installed, use a blank screen.
[ -f /usr/bin/convert ] &&
rm -f /tmp/base.png && scrot -m -z /tmp/base.png &&
pgrep -x dunst && notify-send -i security-high-symbolic.symbolic "Locking computer..." &&
convert /tmp/base.png -grayscale rec709luma -blur 0x8 /tmp/locked.png #grayscale
#convert /tmp/base.png -level 25%\! -blur 0x8 /tmp/locked.png #less color
#convert /tmp/base.png +level-colors ,Teal -blur 0x8 /tmp/locked.png #tealscale
#convert /tmp/base.png +level-colors ,Red -blur 0x8 /tmp/locked.png #redscale

#fprintled 2 red &

i3lock -b -f -c 000000 -i /tmp/locked.png

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
#maptouchscreen
