#!/bin/bash

if ! [[ -z $(xrandr | grep -E -o "HDMI2 connected") ]]
then
    xrandr --output HDMI2 --auto --above eDP1
else
    xrandr --output HDMI2 --off
fi

if ! [[ -z $(xrandr | grep -E -o "DP1 connected") ]]
then
    xrandr --output DP1 --auto --left-of eDP1
else
    xrandr --output DP1 --off
fi

# Calibrate touchscreen
maptouchscreen

i3-msg restart
